eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhosttererfgh:876145/eureka/
  instance:
    hostname: localhostdfgdffgh
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment-service/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order-service/bookOrder
