
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment-service/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order-service/bookOrder
